# Generated by Django 3.0.2 on 2020-03-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerEvent',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
