# Generated by Django 3.0.2 on 2020-03-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_managerevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerevent',
            name='event_ID',
        ),
        migrations.RemoveField(
            model_name='managerevent',
            name='m_username',
        ),
        migrations.DeleteModel(
            name='CustomerEvent',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='ManagerEvent',
        ),
    ]
