# Generated by Django 3.0.2 on 2020-03-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20200307_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=20)),
                ('event_duration', models.IntegerField()),
                ('event_time', models.TimeField()),
                ('event_date', models.DateField()),
                ('event_venue', models.CharField(max_length=15)),
                ('event_description', models.TextField()),
                ('ticket_price', models.IntegerField()),
                ('previous_event_image_filelocation', models.ImageField(upload_to='../static/images/')),
                ('event_video_filelocation', models.ImageField(upload_to='../static/videos/')),
                ('event_contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ManagerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_event_status', models.CharField(max_length=15)),
                ('event_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Event')),
                ('m_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_status', models.CharField(max_length=15)),
                ('c_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Customer')),
                ('event_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Event')),
            ],
        ),
    ]
