# Generated by Django 3.0.2 on 2020-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20200307_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_video_filelocation',
            field=models.ImageField(upload_to='media/videos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='previous_event_image_filelocation',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
