# Generated by Django 3.0.2 on 2020-03-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20200307_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_images', models.ImageField(upload_to='media/more-images')),
                ('event_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Event')),
            ],
        ),
    ]
