# Generated by Django 3.0.2 on 2020-03-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_video_filelocation',
            field=models.FileField(upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='previous_event_image_filelocation',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='more_images',
            field=models.ImageField(upload_to='more-images'),
        ),
    ]
