# Generated by Django 3.0.2 on 2020-03-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20200308_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AD_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Admin')),
                ('event_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Event')),
            ],
        ),
    ]
