# Generated by Django 3.0.2 on 2020-03-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_adminevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerevent',
            name='c_username',
        ),
        migrations.RemoveField(
            model_name='customerevent',
            name='event_ID',
        ),
        migrations.RemoveField(
            model_name='images',
            name='event_ID',
        ),
        migrations.RemoveField(
            model_name='managerevent',
            name='event_ID',
        ),
        migrations.RemoveField(
            model_name='managerevent',
            name='m_username',
        ),
        migrations.DeleteModel(
            name='AdminEvent',
        ),
        migrations.DeleteModel(
            name='CustomerEvent',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='ManagerEvent',
        ),
    ]
