# Generated by Django 3.0.2 on 2020-03-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('event_venue', models.CharField(max_length=15)),
                ('event_time', models.TimeField()),
                ('event_date', models.DateField()),
            ],
        ),
    ]
