# Generated by Django 3.0.2 on 2020-03-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_auto_20200314_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('event_venue', models.CharField(max_length=15)),
                ('event_cost', models.IntegerField()),
                ('event_time', models.TimeField()),
                ('event_date', models.DateField()),
                ('event_status', models.CharField(max_length=15)),
                ('m_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Manager')),
            ],
        ),
    ]
