# Generated by Django 3.0.2 on 2020-04-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_customerevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerevent',
            name='m_username',
            field=models.CharField(max_length=15),
        ),
    ]
