# Generated by Django 3.0.2 on 2020-04-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_auto_20200426_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='time',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
