# Generated by Django 3.0.2 on 2020-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200305_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=20)),
                ('event_duration', models.IntegerField()),
                ('event_time', models.TimeField()),
                ('event_date', models.DateField()),
                ('event_venue', models.CharField(max_length=15)),
                ('event_description', models.TextField()),
                ('ticket_price', models.IntegerField()),
                ('previous_event_image_filelocation', models.ImageField(height_field='65', upload_to='images/', width_field='65')),
                ('event_video_filelocation', models.ImageField(upload_to='videos/')),
                ('event_contact_no', models.IntegerField()),
            ],
        ),
    ]
