# Generated by Django 3.0.2 on 2020-03-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
