# Generated by Django 3.0.2 on 2020-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20200307_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_video_filelocation',
            field=models.FileField(upload_to='media/videos'),
        ),
    ]
