# Generated by Django 3.0.2 on 2020-03-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
