# Generated by Django 3.0.2 on 2020-03-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_customerevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerEvent',
        ),
    ]
